
INSERT INTO EMPLOYEE(ID, FIRST_NAME, LAST_NAME, HIRE_DATE, BOSS_ID) VALUES ('1', 'Mitsugu', 'Hiramatsu', '2019-04-01', null);
INSERT INTO EMPLOYEE(ID, FIRST_NAME, LAST_NAME, HIRE_DATE, BOSS_ID) VALUES ('2', 'Akihiro', 'Katano', '2019-04-01', '1');
INSERT INTO EMPLOYEE(ID, FIRST_NAME, LAST_NAME, HIRE_DATE, BOSS_ID) VALUES ('3', 'Isao', 'Okushima', '2019-04-01', '2');
INSERT INTO EMPLOYEE(ID, FIRST_NAME, LAST_NAME, HIRE_DATE, BOSS_ID) VALUES ('4', 'Hiroyuki', 'Yamamoto', '2019-04-01', '2');
INSERT INTO EMPLOYEE(ID, FIRST_NAME, LAST_NAME, HIRE_DATE, BOSS_ID) VALUES ('5', 'Yusuke', 'Abe', '2019-04-01', '2');
INSERT INTO EMPLOYEE(ID, FIRST_NAME, LAST_NAME, HIRE_DATE, BOSS_ID) VALUES ('6', 'Yoshinobu', 'Nakayama', '2019-04-01', '2');
INSERT INTO EMPLOYEE(ID, FIRST_NAME, LAST_NAME, HIRE_DATE, BOSS_ID) VALUES ('7', 'Riichiro', 'Toyomura', '2019-04-01', '2');
INSERT INTO EMPLOYEE(ID, FIRST_NAME, LAST_NAME, HIRE_DATE, BOSS_ID) VALUES ('8', 'Nozomu', 'Sugiyama', '2019-04-01', '2');
INSERT INTO EMPLOYEE(ID, FIRST_NAME, LAST_NAME, HIRE_DATE, BOSS_ID) VALUES ('9', 'Kenta', 'Kosugi', '2019-04-01', '2');


DELETE FROM EMPLOYEE