version: 2
  jobs:
      build:
          docker:
            - image: circleci/openjdk:10-jdk-browsers
          steps:
            - checkout
            - run: mvn dependency:go-offline
            - restore_cache:
                key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
            - save_cache:
                paths:
                  - ~/.m2
                key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
            - run: mvn package
            - store_test_results:
                path: target/surefire-reports
            - store_artifacts:
                path: target/employee-thorntail.jar